### ISSUE TITLE
Colon instead of semicolon

### ISSUE THREAD

**Issue by liborsobotka** [ptupitsyn/ignite-net-examples#4]
Hello, 

I think there is an error in ignite-net-example. There is used colon instead of semicolon as jars separator.
It didn't work for me, but when I changed this. it worked properly.
Exact line is  

https://github.com/ptupitsyn/ignite-net-examples/blob/da3c230361cddbb8840fe32d57deec45f0cf09ec/REST-API-config/Program.cs#L18

**Comment by ptupitsyn** [comment]
@liborsobotka this separator is OS-specific, `;` on Windows, `:` on Linux and macOS. I've updated the code accordingly. Thanks for the report!

**Comment by liborsobotka** [comment]
@ptupitsyn Thank you for explanation.
