### ISSUE TITLE
type casting ICache to ICacheclient

### ISSUE THREAD

**Issue by MatheswaranSagadevan** [ptupitsyn/ignite-net-examples#5]
Hi,
I have a requirement to use near cache.
I have server node with icache ignite. but client side, my outer most wrapper is ICacheClient. so internally i created an object ICache type of near cache, but i want to type cast it to ICacheclient so that the consumer wrappers will use the ICacheClient.

warning:
I know when we type cast, ICache to ICacheClient some api methods will not be available.
also, if we simply do explicit casting, it just returns null.

Any idea asap would be appreciated.

```
 public Apache.Ignite.Core.Client.Cache.ICacheClient<string, object> InitIgniteCache()
    {
      try
      {
        var cfg = new IgniteClientConfiguration
        {
          Endpoints = new[] { cacheUrl }
        };
        string path = Path.Combine(@"C:\mypath\apache-ignite-2.9.1-bin\config", "default-client-config.xml");
        var client = Ignition.TryGetIgnite() ?? Ignition.Start(path);
        // Create a near-cache configuration
        var nearCfg = new NearCacheConfiguration
        {
          // Use LRU eviction policy to automatically evict entries
          // from near-cache, whenever it reaches 100_000 in size.
          EvictionPolicy = new LruEvictionPolicy()
          {
            MaxSize = 10,
            MaxMemorySize = 20000
          }
        };


        // get the cache named "myCache" and create a near cache for it
        igniteCache = (Apache.Ignite.Core.Client.Cache.ICacheClient<string, object>)client.GetOrCreateNearCache<string, object>("myCache", nearCfg);
      }
      catch (Exception e)
      {
        logger.LogError($"Error initializing Apache Ignite: {e.Message}");
      }
      return igniteCache;
    }
```

Thanks,
Mathes

**Comment by ptupitsyn** [comment]
`ICacheClient` is for Thin Client mode; `ICache` is for Thick Client and Server modes.
Those two interfaces are not related, you can't cast one to another, even though some of the methods have the same signature.

If you require an abstraction over thick and thin modes, I can suggest creating another common interface and corresponding implementations for both modes.

**Comment by MatheswaranSagadevan** [comment]
yep
