### ISSUE TITLE
Thin client + Near cache ?? https://issues.apache.org/jira/browse/IGNITE-13037

### ISSUE THREAD

**Issue by MatheswaranSagadevan** [ptupitsyn/ignite-net-examples#6]
Below is my requirement:
1) I will have one ignite server node
2) I will have many client nodes. But my client should not depend on the JVM. So I prefer the Thin Client.
3) And in client does not need to go over network for every operation. so ideally client should hold data itself and when entries are not in use, the entries should be evicted/expired only from client side.
4) Later when the request for expired entries comes to client then client will go to server and refetch those data.

for my above requirement, NearCache is suitable but it is not coming with ThinClient.
Any idea how to achieve the above requirement will help me in great.

**Comment by ptupitsyn** [comment]
Currently Ignite.NET thin client has no built-in way to achieve this.
However, this should be possible by adding [Microsoft.Extensions.Caching.Memory.MemoryCache](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.memory.memorycache?view=dotnet-plat-ext-5.0) in front of Ignite thin client cache.

**Comment by MatheswaranSagadevan** [comment]
could you please elaborate little more? plz
When we implement with extension, do we need to manage the expiry and eviction policies ?
In case if an entry is removed from server, but local in memory keeps then how the synchronization happens? how does server ask client to remove its local entry.

**Comment by ptupitsyn** [comment]
Hi @MatheswaranSagadevan! This is a personal repository, and it does not represent Apache Ignite project. I'm glad to help with any Ignite questions when I can, but it would be better to ask them in official Ignite support channels, so that all community members can participate: https://ignite.apache.org/community/resources.html

Thanks!
