### ISSUE TITLE
SSL configuration with .Net Thin client

### ISSUE THREAD

**Issue by jojopeter** [ptupitsyn/ignite-net-examples#7]
Hi Pavel Tupitsyn,
I am using .Net thin client(apache.ignite package and IgniteClientConfiguration class). Trying to configure SSL for Thin Clients in following manner.

```
      var cfg = new IgniteClientConfiguration
      {
        Endpoints = new[] { CacheUrl },
        SslStreamFactory = new SslStreamFactory
        {
          CertificatePath = ".../certs/client.pfx",
          CertificatePassword = "password",
        }
      };
      igniteClient = Ignition.StartClient(cfg);
```
	  
I could specify the 'CertificatePath' refering to a client certificate. Is there a way to provide a 'Root Certificate' also in thin client?
I can see that ignite server side configuration(Node level settings) has 'trustStoreFilePath' to point to a root certificate. We are wondering how the server side certificate is getting validated at thin client if the 'Root certificate' path is not provided.

Any help on this is greatly appreciated.

Thanks, Jojo Peter

**Comment by ptupitsyn** [comment]
@jojopeter I'm not sure if I understand the question fully, but you can provide your own `ISslStreamFactory` which loads certificates from anywhere. There is only one method to implement, `SslStream Create(Stream stream, string targetHost)`.

**Comment by jojopeter** [comment]
@ptupitsyn , thanks for your reply.
Sorry for the confusion. I am trying to understand whether the .net thin client has the capability to validate the server certificate.

Thanks.

**Comment by ptupitsyn** [comment]
@jojopeter yes, .NET thin client can validate server certificates.

**Comment by ptupitsyn** [comment]
Closing the issue. This is a personal repository, and it does not represent Apache Ignite project. I'm glad to help with any Ignite questions when I can, but it would be better to ask them in official Ignite support channels, so that all community members can participate: https://ignite.apache.org/community/resources.html

Thanks!

**Comment by jojopeter** [comment]
@ptupitsyn , thanks for your help on this. 
I could resolve the issue with thin client server side certificate validation.
