### ISSUE TITLE
Does Ignite configure Physical RAM or Virtual Memory ?

### ISSUE THREAD

**Issue by MatheswaranSagadevan** [ptupitsyn/ignite-net-examples#8]
```
 DefaultDataRegionConfiguration = new DataRegionConfiguration
                    {
                        Name = "Default_Region",
                        PersistenceEnabled = true,
                        InitialSize = 11L * 1024 * 1024,
                        MaxSize = 15L * 1024 * 1024,                        
                    }
```
in the above, when we configure the Inital and max size of the RAM, does it really mean the physical RAM ? or Virtual ??

**Comment by ptupitsyn** [comment]
Hi @MatheswaranSagadevan , this is my personal repository. I'm glad to help with any Ignite questions when I can,
but it would be better to ask them in official Ignite support channels, so that all community members can participate:
https://ignite.apache.org/community/resources.html

Thanks!
